# Generated by Django 4.2.1 on 2023-11-19 12:26

import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_points', models.IntegerField(blank=True, default=0)),
                ('black_points', models.IntegerField(blank=True, default=0)),
                ('positions', models.JSONField(blank=True, default=api.utils.default_game_positions)),
                ('en_passant', models.CharField(blank=True, max_length=2)),
                ('castling', models.CharField(blank=True, default='KQkq', max_length=4)),
                ('turn', models.CharField(blank=True, default='w', max_length=1)),
                ('result', models.CharField(blank=True, max_length=40)),
                ('king_check', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RankingGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_started', models.BooleanField(default=False)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_black', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', null=True, upload_to=api.utils.create_avatar_name)),
                ('rating', models.IntegerField(default=800)),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('loses', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=1)),
                ('positions', models.JSONField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('new_pos', models.CharField(max_length=4)),
                ('old_pos', models.CharField(max_length=4)),
                ('move', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.game')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_player', models.CharField(blank=True, max_length=64)),
                ('black_player', models.CharField(blank=True, max_length=64)),
                ('game_started', models.BooleanField(default=False)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.CharField(blank=True, max_length=64)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
    ]
