# Generated by Django 4.2.1 on 2023-10-28 20:22

import api.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.JSONField(blank=True, default=api.utils.default_game_positions, max_length=350)),
                ('turn', models.CharField(blank=True, default='w', max_length=1)),
                ('result', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='points',
            new_name='rating',
        ),
        migrations.CreateModel(
            name='RankingGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('black_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('game_started', models.BooleanField(default=False)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_black', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.JSONField(max_length=350)),
                ('turn', models.CharField(max_length=1)),
                ('move', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='GuestGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('white_player', models.CharField(blank=True, max_length=64)),
                ('black_player', models.CharField(blank=True, max_length=64)),
                ('white_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('black_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('game_started', models.BooleanField(default=False)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.CharField(blank=True, max_length=64)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
    ]
