# Generated by Django 4.2.1 on 2023-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='computergameroom',
            name='black_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='computergameroom',
            name='white_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='guestgameroom',
            name='black_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='guestgameroom',
            name='white_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rankinggameroom',
            name='black_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rankinggameroom',
            name='white_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
