# Generated by Django 4.2.1 on 2023-10-28 21:01

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_rename_points_profile_rating_rankinggameroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='positions',
            field=models.JSONField(blank=True, default=api.utils.default_game_positions),
        ),
        migrations.AlterField(
            model_name='move',
            name='positions',
            field=models.JSONField(),
        ),
    ]
