# Generated by Django 4.2.1 on 2023-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_guestgameroom_game_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='draws',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
