# Generated by Django 4.2.1 on 2023-11-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computergameroom_black_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computergameroom',
            name='black_points',
        ),
        migrations.RemoveField(
            model_name='computergameroom',
            name='white_points',
        ),
        migrations.RemoveField(
            model_name='guestgameroom',
            name='black_points',
        ),
        migrations.RemoveField(
            model_name='guestgameroom',
            name='white_points',
        ),
        migrations.RemoveField(
            model_name='rankinggameroom',
            name='black_points',
        ),
        migrations.RemoveField(
            model_name='rankinggameroom',
            name='white_points',
        ),
        migrations.AddField(
            model_name='game',
            name='black_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
