# Generated by Django 4.2.1 on 2023-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_positions_alter_move_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='castling',
            field=models.CharField(blank=True, default='KQkq', max_length=4),
        ),
    ]
