# Generated by Django 4.2.1 on 2023-10-22 00:16

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_room_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_player', models.CharField(blank=True, max_length=64)),
                ('black_player', models.CharField(blank=True, max_length=64)),
                ('white_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('black_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('game_state', models.JSONField(blank=True, default=api.models.default_game_state)),
                ('turn', models.CharField(blank=True, default='w', max_length=1)),
                ('room_id', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('game_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuestGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_player', models.CharField(blank=True, max_length=64)),
                ('black_player', models.CharField(blank=True, max_length=64)),
                ('white_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('black_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('game_state', models.JSONField(blank=True, default=api.models.default_game_state)),
                ('turn', models.CharField(blank=True, default='w', max_length=1)),
                ('room_url', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('game_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('black_timer', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('game_state', models.JSONField(blank=True, default=api.models.default_game_state)),
                ('turn', models.CharField(blank=True, default='w', max_length=1)),
                ('room_url', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('game_started', models.BooleanField(default=False)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
