# Generated by Django 4.2.1 on 2023-11-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_castling'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='en_passant',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
