# Generated by Django 4.2.1 on 2023-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_en_passant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
