# Generated by Django 4.2.1 on 2023-10-22 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_room_id_computergameroom_room_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computergameroom',
            name='room_url',
        ),
        migrations.RemoveField(
            model_name='guestgameroom',
            name='room_url',
        ),
        migrations.RemoveField(
            model_name='usergameroom',
            name='room_url',
        ),
        migrations.AlterField(
            model_name='computergameroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guestgameroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergameroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
    ]
