# Generated by Django 4.2.1 on 2023-10-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_computergameroom_id_alter_guestgameroom_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computergameroom',
            old_name='black_player',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='computergameroom',
            name='game_started',
        ),
        migrations.RemoveField(
            model_name='computergameroom',
            name='white_player',
        ),
    ]
