# Generated by Django 4.2.1 on 2024-03-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='avatar.png', null=True, upload_to=user.utils.models.create_avatar_name)),
                ('rating', models.IntegerField(default=800)),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('loses', models.IntegerField(blank=True, default=0)),
                ('draws', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
